name: Duels CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Build]')"

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      # Checkout CosmoCraft-Team/PharBuilder
      - name: Checkout PharBuilder
        uses: actions/checkout@v2
        with:
          repository: CosmoCraft-Team/PharBuilder
          token: ${{ secrets.CC_TOKEN }}
          path: vendor/PharBuilder
      - name: Build
        run: |
          echo Building...
          chmod +x vendor/PharBuilder/BuildScript.php
          php -dphar.readonly=0 vendor/PharBuilder/BuildScript.php --make "" --out vendor/PharBuilder/Duels.phar
          echo Build completed!
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: Builder
          path: vendor/PharBuilder/Duels.phar